In [2]:
import requests
import pandas as pd
import numpy as np

In [3]:
df_pokemon = pd.DataFrame(columns = ['id', 'name', 'base_xp', 'height', 'weight', 'nabilities', 'abilities', 'meanstats', 'stats', 'ntypes', 'types', 'islegendary'])


for i in range(1, 899):
    
    #Requisições na API
    
    api = f'https://pokeapi.co/api/v2/pokemon/{i}'
    res = requests.get(api)
    poke = res.json()

    api2 = f'https://pokeapi.co/api/v2/pokemon-species/{i}'
    res2 = requests.get(api2)
    poke2 = res2.json()
    
    # Infos básicas

    id = poke['id']
    name = poke['name']
    base_xp = poke['base_experience']
    heightcm = poke['height'] * 10
    weightkg = poke['weight'] / 10


    # Habilidades

    abilities = poke['abilities']
    abilities = [ability['ability']['name'] for ability in abilities]
    nabilities = len(abilities)

    # Status Base
    x = poke['stats']
    stats = {}
    for stat in x:
        stats[stat['stat']['name']] = stat['base_stat']
    meanstats = int(sum(stats.values())/len(stats))

    # Tipos
    types = poke['types']
    types = [_['type']['name'] for _ in types]
    ntypes = len(types)

    # É Lendário
    if poke2['is_legendary'] or poke2['is_mythical']: islegendary = 1
    else: islegendary = 0
        
    pokemon = {'id':id,
           'name':name,
           'base_xp':base_xp,
           'height':heightcm,
           'weight':weightkg, 
           'nabilities':nabilities,
           'abilities':abilities,
           'meanstats':meanstats,
           'stats':stats,
           'ntypes':ntypes,
           'types':types,
           'islegendary':islegendary}
    
    df_pokemon = df_pokemon.append(pokemon, ignore_index=True)

df_pokemon = df_pokemon.set_index('id')

In [4]:
df_pokemon

,name,base_xp,height,weight,nabilities,abilities,meanstats,stats,ntypes,types,islegendary
id,,,,,,,,,,,
1,bulbasaur,64,70,6.9,2,"[overgrow, chlorophyll]",53,"{'hp': 45, 'attack': 49, 'defense': 49, 'speci...",2,"[grass, poison]",0
2,ivysaur,142,100,13.0,2,"[overgrow, chlorophyll]",67,"{'hp': 60, 'attack': 62, 'defense': 63, 'speci...",2,"[grass, poison]",0
3,venusaur,263,200,100.0,2,"[overgrow, chlorophyll]",87,"{'hp': 80, 'attack': 82, 'defense': 83, 'speci...",2,"[grass, poison]",0
4,charmander,62,60,8.5,2,"[blaze, solar-power]",51,"{'hp': 39, 'attack': 52, 'defense': 43, 'speci...",1,[fire],0
5,charmeleon,142,110,19.0,2,"[blaze, solar-power]",67,"{'hp': 58, 'attack': 64, 'defense': 58, 'speci...",1,[fire],0
...,...,...,...,...,...,...,...,...,...,...,...
894,regieleki,290,120,145.0,1,[transistor],96,"{'hp': 80, 'attack': 100, 'defense': 50, 'spec...",1,[electric],1
895,regidrago,290,210,200.0,1,[dragons-maw],96,"{'hp': 200, 'attack': 100, 'defense': 50, 'spe...",1,[dragon],1
896,glastrier,290,220,800.0,1,[chilling-neigh],96,"{'hp': 100, 'attack': 145, 'defense': 130, 'sp...",1,[ice],1
897,spectrier,290,200,44.5,1,[grim-neigh],96,"{'hp': 100, 'attack': 65, 'defense': 60, 'spec...",1,[ghost],1
898,calyrex,250,110,7.7,1,[unnerve],83,"{'hp': 100, 'attack': 80, 'defense': 80, 'spec...",2,"[psychic, grass]",1

In [7]:
df_pokemon.to_csv('pokemon.csv')